import { StyleSheet } from 'react-native';

export const localGameStyles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 14,
    paddingVertical: 12,
    position: 'relative',
    gap: 12,
  },
  boardArea: {
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
  },
  boardCluster: {
    position: 'relative',
    alignSelf: 'center',
  },
  topClockAnchor: {
    position: 'absolute',
    zIndex: 8,
    left: 0,
  },
  bottomClockAnchor: {
    position: 'absolute',
    zIndex: 8,
    right: 0,
  },
  boardFrame: {
    position: 'relative',
    borderRadius: 4,
    overflow: 'hidden',
  },
  captureFlash: {
    position: 'absolute',
    borderRadius: 12,
    borderWidth: 2,
    pointerEvents: 'none',
  },
  statusCard: {
    width: '100%',
  },
  historyPanel: {
    width: '100%',
    borderRadius: 16,
    borderWidth: 1,
    overflow: 'hidden',
  },
  historyHeader: {
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderBottomWidth: 1,
  },
  historyRow: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderBottomWidth: 1,
  },
  promotionBackdrop: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 30,
    paddingHorizontal: 16,
  },
  promotionPanel: {
    width: '100%',
    maxWidth: 420,
    borderRadius: 14,
    borderWidth: 1,
    paddingHorizontal: 16,
    paddingVertical: 16,
    gap: 12,
  },
  promotionOption: {
    borderWidth: 1,
    borderRadius: 14,
    width: 72,
    height: 72,
    alignItems: 'center',
    justifyContent: 'center',
  },
  endOverlay: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 35,
    paddingHorizontal: 18,
  },
  endCard: {
    width: '100%',
    maxWidth: 420,
    borderRadius: 18,
    borderWidth: 1,
    paddingVertical: 18,
    paddingHorizontal: 16,
    gap: 12,
  },
  clockCard: {
    borderRadius: 10,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  actionsRow: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 10,
  },
});
