import { StyleSheet } from 'react-native';

export const localGameStyles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 14,
    paddingVertical: 12,
    position: 'relative',
    gap: 12,
  },
  boardArea: {
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
  },
  boardCluster: {
    position: 'relative',
    alignSelf: 'center',
  },
  topClockAnchor: {
    position: 'absolute',
    zIndex: 8,
    left: 0,
  },
  bottomClockAnchor: {
    position: 'absolute',
    zIndex: 8,
    right: 0,
  },
  topPlayerBadgeAnchor: {
    position: 'absolute',
    zIndex: 8,
    left: 0,
    right: 0,
    alignItems: 'flex-end',
  },
  bottomPlayerBadgeAnchor: {
    position: 'absolute',
    zIndex: 8,
    left: 0,
  },
  playerBadge: {
    alignItems: 'flex-start',
    justifyContent: 'center',
  },
  boardFrame: {
    position: 'relative',
    borderRadius: 4,
    overflow: 'hidden',
  },
  captureFlash: {
    position: 'absolute',
    borderRadius: 12,
    borderWidth: 2,
    pointerEvents: 'none',
  },
  statusCard: {
    width: '100%',
  },
  historyPanel: {
    width: '100%',
    borderRadius: 16,
    borderWidth: 1,
    overflow: 'hidden',
  },
  historyHeader: {
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderBottomWidth: 1,
  },
  historyRow: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderBottomWidth: 1,
  },
  modalBackdrop: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 35,
    paddingHorizontal: 15,
    paddingVertical: 15,
  },
  modalCard: {
    width: '100%',
    maxWidth: 400,
    borderRadius: 20,
    borderWidth: 1,
    paddingHorizontal: 40,
    paddingTop: 32,
    paddingBottom: 28,
    gap: 22,
  },
  modalActionsRow: {
    marginTop: 8,
    gap: 10,
    flexWrap: 'nowrap',
    justifyContent: 'flex-end',
  },
  modalContentInset: {
    paddingHorizontal: 12,
  },
  promotionOption: {
    borderWidth: 1,
    borderRadius: 18,
    flex: 1,
    minWidth: 0,
    aspectRatio: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  endOverlay: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 35,
    paddingHorizontal: 18,
  },
  endCard: {
    width: '100%',
    maxWidth: 420,
    borderRadius: 18,
    borderWidth: 1,
    paddingVertical: 18,
    paddingHorizontal: 16,
    gap: 12,
  },
  clockCard: {
    borderRadius: 10,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  actionsRow: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 18,
    paddingHorizontal: 14,
    paddingTop: 18,
  },
});
